# -*- coding: utf-8 -*-
"""Árvores2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1vLP3pWjYH_9lXThQGaNKvToAWp1gdsEB
"""

import pandas as pd
from sklearn.model_selection import train_test_split 
from sklearn.tree import DecisionTreeClassifier 
from sklearn import metrics

from google.colab import drive
from google.colab import files
drive.mount ('/content/gdrive', force_remount = True)
dirRaiz = "/content/gdrive/My Drive/"
dirBase = dirRaiz + "Colab Notebooks/datasets/"

col_names = ['pregnant', 'glucose', 'bp', 'skin', 'insulin', 'bmi', 'pedigree', 'age', 'label']

pima = pd.read_csv(dirBase+"pima-indians-diabetes.csv", header=None, names=col_names)

pima.head

feature_cols = ['pregnant', 'insulin', 'bmi', 'age','glucose','bp','pedigree']
X = pima[feature_cols] # Atributos
y = pima.label # Classe (alvo)

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=1) # 70% treino e 30% teste

# Criando o classificador
clf = DecisionTreeClassifier()

# Ajustando
clf = clf.fit(X_train,y_train)

# Predizendo
y_pred = clf.predict(X_test)

print("Accuracy:",metrics.accuracy_score(y_test, y_pred))

from six import StringIO  
from IPython.display import Image  
from sklearn.tree import export_graphviz
import pydotplus
dot_data = StringIO()
export_graphviz(clf, out_file=dot_data,  
                filled=True, rounded=True,
                special_characters=True, feature_names = feature_cols,class_names=['0','1'])
graph = pydotplus.graph_from_dot_data(dot_data.getvalue())  
graph.write_png('diabetes.png')
Image(graph.create_png())